name: spatialdata-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - pip
  - numpy
  - pandas
  - matplotlib
  - notebook
  - jupyter
  - spatialdata==0.2.2
  - spatialdata-io
  - napari-spatialdata
  - squidpy
  - pip:
    - spatialdata-plot==0.2.6
    - PyQt5 # for napari
