name: spatialdata-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - pip
  - numpy
  - pandas
  - matplotlib
  - notebook
  - jupyter
  - spatialdata==0.2.2
  - spatialdata-io
  - napari-spatialdata
  - squidpy
  - pip:
    - git+https://github.com/scverse/spatialdata-plot.git@main
    - PyQt5 # for napari