name: spatialdata-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - pip
  - numpy
  - pandas
  - matplotlib
  - notebook
  - jupyter
  - jupyter_contrib_nbextensions # for auto-completion 
  - squidpy
  - pytest
  - pip:
    - spatialdata==0.2.3
    - spatialdata-io==0.1.5
    - napari-spatialdata==0.5.3
    - spatialdata-plot==0.2.6
    - spatial-image==1.1.0
    - PyQt5 # for napari
    - lxml_html_clean # for napari
    - jupyter-black
